export const COUNTRIES = [
    // Middle East
    "United Arab Emirates",
    "Saudi Arabia",
    "Qatar",
    "Kuwait",
    "Bahrain",
    "Oman",
    "Turkey",
    "Israel",
    "Jordan",
    "Lebanon",

    // Europe
    "United Kingdom",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Netherlands",
    "Switzerland",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Belgium",
    "Austria",
    "Greece",
    "Portugal",
    "Ireland",
    "Poland",
    "Czech Republic",
    "Hungary",
    "Romania"
];

export const PHONE_CODES = [
    { code: "+86", country: "China" },
    { code: "+1", country: "USA/Canada" },
    { code: "+44", country: "UK" },
    { code: "+971", country: "UAE" },
    { code: "+966", country: "Saudi Arabia" },
    { code: "+974", country: "Qatar" },
    { code: "+965", country: "Kuwait" },
    { code: "+973", country: "Bahrain" },
    { code: "+968", country: "Oman" },
    { code: "+90", country: "Turkey" },
    { code: "+972", country: "Israel" },
    { code: "+962", country: "Jordan" },
    { code: "+961", country: "Lebanon" },
    { code: "+49", country: "Germany" },
    { code: "+33", country: "France" },
    { code: "+39", country: "Italy" },
    { code: "+34", country: "Spain" },
    { code: "+31", country: "Netherlands" },
    { code: "+41", country: "Switzerland" },
    { code: "+46", country: "Sweden" },
    { code: "+47", country: "Norway" },
    { code: "+45", country: "Denmark" },
    { code: "+358", country: "Finland" },
    { code: "+32", country: "Belgium" },
    { code: "+43", country: "Austria" },
    { code: "+30", country: "Greece" },
    { code: "+351", country: "Portugal" },
    { code: "+353", country: "Ireland" },
    { code: "+48", country: "Poland" },
    { code: "+420", country: "Czech Republic" },
    { code: "+36", country: "Hungary" },
    { code: "+40", country: "Romania" },
    { code: "+852", country: "Hong Kong" },
    { code: "+853", country: "Macau" },
    { code: "+886", country: "Taiwan" },
    { code: "+65", country: "Singapore" },
    { code: "+60", country: "Malaysia" },
    { code: "+81", country: "Japan" },
    { code: "+82", country: "South Korea" },
    { code: "+61", country: "Australia" },
    { code: "+64", country: "New Zealand" }
];
